### ISSUE TITLE
CardElement intermittently doesn't appear on Safari Mobile

### ISSUE THREAD

**Issue by GabeIsman** [stripe/react-stripe-elements#60] opened 2017-08-16 15:35 UTC
I received a report from a user that the CardElement never rendered on Safari (up to date, new iPhone). This was using version 0.0.2 of the library. This occurred on this page: https://www.themarshallproject.org/support-us. 

From the user: "I could not enter information on the line under “credit card” It simply would not make the keyboard available or allow me to click on/place a cursor/etc. on the space under “credit card” when that was selected. It was totally blank. After a couple of attempts poking around on the screen, Safari just crashed. Twice."

This sounds possibly related to #35. I was not able to reproduce, as with that bug. This is now the third report I've had of something similar though.

**Comment by cweiss-stripe** [comment] 2017-08-18 15:27
Hi @GabeIsman thank you for the report. Unfortunately, I was also not able to reproduce this one yet. We will keep investigating what could be going on here. If you get further reports or find more details, please share them here.

**Comment by jenan-stripe** [comment] 2017-10-02 19:15
I'm going to close as a duplicate of #35. Please let us know if you can repro!

**Closed by jenan-stripe** 2017-10-02 19:15 UTC
Labels: bug, needs more info
