### ISSUE TITLE
The first tap focusing on the fake inputs  in IOS Safari

### ISSUE THREAD

**Issue by lightofdavinci** [stripe/react-stripe-elements#453] opened 2019-11-01 19:30 UTC
<img width="541" alt="Screen Shot 2019-11-01 at 12 04 11 PM" src="https://user-images.githubusercontent.com/16696703/68049282-bf3daa80-fc9f-11e9-899f-94ff4b70de96.png">
The first tap outside of InputElement, but inside of StripeElement focusing on the fake inputs in IOS Safari (iPad). We are using inputs with the height that is greater than in provided examples (attached SS). I could reproduce the same behavior on the stripes elements examples when touched the bottom-border of the inputs. It wouldn't be a big problem if it wasn't triggering appearing of the virtual keyboard and then toggling between invisible inputs. It only happens on the very first interaction after mounting elements. As soon as the InputElement was focused it's impossible to get focus on the fake input within the same StripeElement.

**Comment by mbarrett-stripe** [comment] 2019-11-01 20:03
Hey there - it's hard to tell just from your screenshot, but if you're using hovering labels over an element, we recommend putting the CSS `pointer-events: none` on the label. This is so that user clicks will go directly to the input, as a workaround for a change in newer Safari (iOS13+) which prevents us from properly passing the focus into the Stripe Element.

For more info, see this support article: https://support.stripe.com/questions/ios-13-and-stripe-elements-label-focus-issue

If you're not using overlaid labels, it'd be super helpful if you could provide a minimum viable recreation in a code sandbox like https://codesandbox.io/

**Comment by lightofdavinci** [comment] 2019-11-01 20:59
Hey, thank you for the quick response. I forked existing project and added padding top to the inputs here - https://jsfiddle.net/lightofdavinci/gpty23kx/4/ .
Expected behavior:
 1) Choose any input block
 2) Tap or click on the input placeholder to trigger input focus
 3) Tap or click outside of the block to trigger blur
 4) Tap or click on the white padding space above input
After these steps the input will be focused
Then choose another stripe block or reload the page and tap at that white top space from the very beginning. The element will be focused with virtual keyboard, but the input won't

**Comment by mbarrett-stripe** [comment] 2019-11-27 19:07
Hey @lightofdavinci, this is likely happening due to a [change in Safari](https://developer.apple.com/documentation/safari_release_notes/safari_13_release_notes):

> Changed the behavior for third party iframes to prevent them automatically navigating the page.

The implication here is that in Safari, an iframe cannot programmatically control focus until the user has explicitly clicked into it, if the iframe is a 3rd party. Stripe Elements uses iframes which are hosted on the Stripe domain in order to alleviate PCI compliance.

You can reproduce this behavior minimally by making one website load an iframe from another domain or port, where the iframe attempts to call `.focus()` on an input. It won't focus until the user has clicked into the frame in Safari.

This is behavior we have recently become aware of and we are tracking the bug internally. We'll prioritize it as we can. As of now, one workaround would be to minimize clickable places that aren't the input itself, such as labels. Clicking the input directly should result in the right keyboard displaying. It's not perfect, but browser changes can cause a ruckus sometimes 😢 

Since the issues section of this repo is specifically for the React layer on top of Stripe Elements, I'm going to close this issue. If you have further problems you should contact [our support team](https://support.stripe.com/) directly for issues with Stripe Elements.

**Closed by mbarrett-stripe** 2019-11-27 19:07 UTC

**Comment by jojofeng** [comment] 2020-02-24 19:55
Any updates on this? I believe this is also related to the same issue I have been seeing within a React Native Webview; tapping outside of the iframe input but within the StripeElement `div` "focuses" the `div` and brings up a QWERTY keyboard (not a number pad). Thanks!

**Comment by mbarrett-stripe** [comment] 2020-02-25 15:00
That is likely the same issue, yes. We've since contacted the Safari team and reported the exact bug you're mentioning. Unfortunately, no other update I can share at this time.
