### ISSUE TITLE
Classes don't seem to update timely, or correctly.

### ISSUE THREAD

**Issue by MikeKlemarewski** [stripe/react-stripe-elements#429] opened 2019-09-13 00:45 UTC
### Summary

When updating the `classes` prop on an element (specifically the CardElement in my case) I've noticed that the changes don't take place until something else causes the component to re-render. I've also noticed that the classes seem to accumulate, rather than apply the exact classes that are passed in.

I've got what I think is a minimal test case here: https://jsfiddle.net/kxe6a3qm/3/

It's a stripped down CardElement that gets `style` and `classes` passed to it.

When you click the `toggle` button, the text in the element should turn from black to green (using the style prop), and the input should have a border appear and disappear (via the classes prop).

You'll notice if you fill out the form, then click toggle. The text color will change green, but no border appears **until you click into the card input**.

On top of that, it seems like the classes you pass in get accumulated. In this example, I am setting classes like this:

```
<CardElement
  classes={{ base: this.state.border }}
  ...
/>
```

Border gets toggled between the string `border` and `no-border`. So at any one point, the base class should either be `border` or `no-border`. But after toggling the class, then clicking into the card input, you'll notice that both `no-border` and `border` classes are applied.

![stripe](https://user-images.githubusercontent.com/491046/64830396-0b644c80-d585-11e9-971c-f9dc85b32ffa.gif)

This behavior seems odd to me. I would expect the component to re-render when I change the classes prop, and for it to represent exactly what was passed in as the classes prop.

**Comment by oliver-stripe** [comment] 2019-09-23 16:21
@MikeKlemarewski Thanks for the report and repro. We'll take a look.

**Comment by oliver-stripe** [comment] 2019-09-26 21:30
This should be fixed now! The jsfiddle looks like it has the expected behavior now.

**Closed by oliver-stripe** 2019-09-26 21:30 UTC
