### ISSUE TITLE
IOS Safari Moves Input Out Of View

### ISSUE THREAD

**Issue by pizzarob** [stripe/react-stripe-elements#327] opened 2019-03-01 01:39 UTC
Hi. In IOS Safari once a user enters an input and then taps around the field, the input will drop lower and lower. If a user then starts typing again the field will correct itself. I have attached a video of the IOS simulator, but its easier to reproduce on an iphone.

[stripebug.mov.zip](https://github.com/stripe/react-stripe-elements/files/2917578/stripebug.mov.zip)

**Comment by pizza-r0b** [comment] 2019-03-01 17:29
This actually seems to be an issue with stripe elements. Was able to reproduce on the stripe website

![image](https://user-images.githubusercontent.com/5282495/53655262-862ad300-3c04-11e9-8a22-300cc3f162a4.png)

**Comment by asolove-stripe** [comment] 2019-03-03 03:25
Hey @pizza-r0b: yikes, that looks pretty bad, thanks for reporting. 

I tried to download the video but GitHub is either serving it very slow or some other network thing is going wrong and I can't see anything.

I tried reproducing on that page with iOS devices I have on hand and wasn't able to. Can you share a bit about the device/OS version you're using? Also, I tried to reproduce by typing, selecting to copy/paste, and trying to drag within the Element, but didn't see the layout break. Was there some other gesture you were doing that seemed to trigger it to scroll like that?

**Comment by pizza-r0b** [comment] 2019-03-03 04:39
Hey there. It’s actually easier to reproduce on an actual device, but i was able to reproduce on the ios simulator. I have an iphone seven. Once you type into a field you can reproduce by tapping around the label of the current field. It seems like the focus/re-focus makes the input field move down with every tap of the label. Let me know if you need more info.

**Comment by jonah-corbin** [comment] 2019-03-27 05:55
I’m also having this issue on all mobile platforms @asolove-stripe

**Comment by jonah-corbin** [comment] 2019-03-27 17:57
I think I figured it out. I altered the ‘lineHeight’ and that fixed it for me.

**Comment by oliver-stripe** [comment] 2019-06-13 21:45
@pizza-r0b Are you still able to reproduce this? I am not able to with a iOS 12.3.1. Can you tell us the iOS version if you are able to reproduce?

**Comment by Jlevyd15** [comment] 2019-10-02 17:49
@oliver-stripe i’m still able to reproduce this on iOS 13.

**Comment by sashko-stripe** [comment] 2021-03-26 18:36
Closing this as this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js). If you believe this is still important, please re-open it there.

**Closed by sashko-stripe** 2021-03-26 18:36 UTC
