### ISSUE TITLE
Problems with React Native for Web?

### ISSUE THREAD

**Issue by dereksweet** [stripe/react-stripe-elements#219] opened 2018-07-11 19:00 UTC
### Summary

We are using the components with React Native for Web, and we seem to have an issue when touching the inputs for the elements on a mobile device. Seems that we can click into the inputs sometimes, but if we dismiss the keyboard, click on the background of the page, then click the input it won't focus into it. Sometimes takes 5 or 6 presses before it finally gets picked up and focuses on the element. Does not seem to be a problem on the example pages, though, so we are thinking it probably has to do with React Native for Web. We do not know this for certain, however, just assuming since the example pages work fine but our app does not. 

We did come up with a workaround, which is to create a ref to the element and then call `focus()` on that ref when the encapsulating View is clicked. Here is a code snippet: 

```
<View onClick={() => this.cardNumberElement.focus()}>
    <CardNumberElement onReady={(element) => this.cardNumberElement = element} />
</View>
```

### Other information

- Seems to happen in both Chrome and Safari, not specific to either browser
- We have not tested on any Android browsers, just iOS
- react-native-web version 0.8.5
- If the keyboard is up and another non-stripe-element input is in focus, the problem does not seem to happen.

**Comment by asolove-stripe** [comment] 2018-07-16 16:57
Hey @dereksweet, thanks for reporting this! I would guess it is related to assumptions we make that don't fit with React Native for Web, but it's hard to say. Do you by chance have a public url (or a private demo you can email to just me) so that I can try to reproduce?

**Comment by dereksweet** [comment] 2018-07-17 17:14
We are hammering away at a big deadline right now, but when I get a sec I'll see if I can throw together a jsfiddle or something that demonstrates the issue. 

FYI - The same problem exists on the <PaymentRequestButton> element as well. Same workaround works but it throws a warning in a console about using paymentRequest.show() when the button is already there.

**Comment by asolove-stripe** [comment] 2018-09-10 16:44
@dereksweet did you ever figure out a fix or track down a way for us to reproduce?

We're happy to poke at this but haven't been able to reproduce, and admittedly don't know React Native for Web very well.

If it's not an issue any more or you don't have time, definitely no problem though. I'll close this in a few days if we don't hear back, but always happy to dig in if you can help us reproduce.

**Comment by dereksweet** [comment] 2018-09-10 17:05
Thanks for reminding me! I still don't have a public URL or a private demo I can send you, unfortunately. We ended up having so many problems with this package and React Native web we just ended up using your single line credit card widget which the problems were much less apparent with since everything was on one line. 

We were able to eventually get it working with the workaround indicate in the initial report, but then we had big problems where whenever the fields were focused on the scroll position would do some crazy things and elements were moved off the page every time you typed a character. So even if you did manage to get things focused properly, as soon as you typed another character it would scroll to the very bottom of the page. Once we moved to your single line credit card input widget, scrolling to the bottom of the page didn't cause as many issues on mobile browsers since it was the last thing on the page. 

Anyway, you can close this issue if you like. The problems should be quite apparent if you just attempt to use your package with React Native Web and test it on a mobile browser.

**Comment by asolove-stripe** [comment] 2018-09-10 17:11
Ah, I can imagine how the React Native event system might trigger that. I'm glad you got it to an ok state! I didn't try on a page long enough to scroll, thus I missed it. I'm going to close for now since you got to an acceptable solution. But we're happy to take a look if someone else runs into this and needs help.

**Closed by asolove-stripe** 2018-09-10 17:11 UTC

**Comment by asolove-stripe** [comment] 2018-09-11 17:58
@dereksweet FYI I believe this wasn't a React Native issue after all but a bug in iOS 11.4 Safari that [we're debugging in another issue](https://github.com/stripe/react-stripe-elements/issues/244#issuecomment-420363281) that causes this unexpected scroll jump.
