### ISSUE TITLE
CardElement intermittently doesn't appear on Safari

### ISSUE THREAD

**Issue by GabeIsman** [stripe/react-stripe-elements#35] opened 2017-07-13 15:51 UTC
I've had multiple reports (with screenshots) from users of `CardElement` not rendering (just never appears) on Safari (one of them Version 10.1.1 (11603.2.5)). There were no errors in the console. The problem did not persist after a refresh, and I was not able to reproduce it.

I know this is not a terribly helpful bug report, but I thought you should know that I have seen this happen.

**Comment by michelle** [comment] 2017-07-13 15:58
@GabeIsman thanks for the report -- is there a particular integration or webpage that you've seen this on?

**Comment by GabeIsman** [comment] 2017-07-13 16:17
Observed here: https://www.themarshallproject.org/support-us.

**Comment by michelle** [comment] 2017-07-13 16:33
@GabeIsman Thanks! I'll take a look now.

**Comment by michelle** [comment] 2017-07-13 17:04
Interesting -- I could only reproduce this no the first page load. Perhaps it has something to do with a cold cache.

**Comment by michelle** [comment] 2017-07-14 01:31
I can now no longer reproduce this at all, even after disabling / clearing caches :(. I'll try again on a different machine tomorrow.

**Comment by GabeIsman** [comment] 2017-07-14 16:39
Thanks for looking into this @michelle. It was quite puzzling to me as well.

**Comment by fred-stripe** [comment] 2017-07-25 15:55
Hi @GabeIsman have you had any further reports of this? Just poking around and I can't seem to make this happen (tried a couple different things).

**Comment by GabeIsman** [comment] 2017-07-25 17:35
@fred-stripe I haven't had any further reports, but I don't think that I would have. (We have a low volume of Safari users.) I wish I had better guidance for you on how to reproduce. It seems to only happen once, if it does at all.

**Comment by Barnyclark** [comment] 2017-11-03 13:27
Hi @fred-stripe we have just moved over to the new elements library and are having a similar issue. We are getting the following error being reported sporadically to Sentry: 

> Please load Stripe.js (https://js.stripe.com/v3/) on this page to use react-stripe-elements. 

this is despite the fact that the script tag is at the top of the page before the react app is loaded.

It is only happening on mobile safari on iOS 10.3.3 and 11.0.3. I have been unable to recreate this myself, which I realise is unhelpful, but I have the sentry errors if that is useful.

**Comment by tinovyatkin** [comment] 2018-01-12 05:05
The same error using Safari and Stripe Elements v3:
`IntegrationError
We could not retrieve data from the specified Element.
Please make sure the Element you are attempting to use is still mounted.`

at https://transfers.do/book/ (we create Stripe Elements only after 'onload' call for Elements script, so, it's loaded for sure)

Some Sentry statistics on this error:
<img width="327" alt="screenshot 2018-01-12 08 05 03" src="https://user-images.githubusercontent.com/5350898/34860557-5baaa482-f76f-11e7-8b9e-419966044f9a.png">

**Comment by atty-stripe** [comment] 2018-02-07 21:19
@Barnyclark are you still facing that issue? If not, since we're unable to reproduce this issue, we might go ahead and close it.

**Comment by Barnyclark** [comment] 2018-02-09 16:32
Ho @atty-stripe we are still having this issue, it is not restricted to safari though, we receive the error on a small number of requests across all browsers/devices.

**Comment by atty-stripe** [comment] 2018-02-09 20:28
Hmm that's strange -- could you share the Sentry issues please?

**Comment by Barnyclark** [comment] 2018-02-16 18:06
Here is an example: https://sentry.io/share/issue/30833e57245a420987aefd880febc927/

**Comment by atty-stripe** [comment] 2018-02-18 03:02
Thanks @Barnyclark! 

Unfortunately there's little we can deduce from the Sentry issue, since it simply says that Stripe.js didn't load. Are you sure this wasn't a network issue or something else that actually prevented the script from loading? It might be useful to check if `window.Stripe` exists and report that in your logs, so the next time this error pops up you can be sure if this was simply a network issue that prevented the script from loading.

Otherwise we haven't been able to repro this. If you have any more info you can share, would love to see it!

**Comment by jab1000** [comment] 2018-09-05 20:37
Over the past 10ish days we have the same problem with 4 different customers -- all fo them were trying to open the payment page on Safari on their iphone.  Granted no idea what the iOS/Safari version is though.  I agree that it probably is an intermitent network delay on their mobile but would be nice if their was a "way to test" for it even if just to give a message to the user - "please refresh,  an error occurred while setting up the payment page"

**Comment by asolove-stripe** [comment] 2018-09-12 02:09
It appears that this error is always triggered by Stripe.js failing to load over the network or loading in the wrong order. I am inclined to close this issue, since we understand what is causing it, and to use issue #237 as a place to discuss providing some API surface area for applications to be able to catch this error and respond to it in some useful way.

**Closed by asolove-stripe** 2018-09-12 02:09 UTC
Labels: needs more info

**Comment by tuomashatakka** [comment] 2019-10-21 11:50
I ran into today as well. This seems to happen now consistently on Opera too. A couple of weeks ago there were no problems and the codebase hasn't been updated since. There are a couple of network requests to `js.stripe.com` that will never finish.

![Screenshot 2019-10-21 at 13 19 17](https://user-images.githubusercontent.com/5794328/67202547-89800280-f411-11e9-9ff6-14451a57da33.png)

**Comment by kevinswarner** [comment] 2020-04-10 18:36
This has also been occurring in our app that is a NextJS app. It only occurs in Safari and Safari on iOS. It only happens when the user uses the "refresh" button in Safari. If you click in the address bar and click the enter key, it works fine. I notice in the inspector that certain Stripe assets just do not load.

![image](https://user-images.githubusercontent.com/399641/79013886-89d69c00-7b1e-11ea-863f-9a82bd5dbc2b.png)

I originally thought it might be an SSR issue, but I ruled that out by testing a statically deployed site.

Could it be something related to how NextJS is bundling the assets or something to do with how Safari caches certain assets? I am at a loss. I appreciate any suggestions.

**Comment by esetnik** [comment] 2020-04-26 16:02
I’m having the same issue as @kevinswarner.
