### ISSUE TITLE
CVV input requiring more than 3 digits on a VISA

### ISSUE THREAD

**Issue by scottwilson312** [stripe/react-stripe-elements#340] opened 2019-04-04 06:53 UTC
I've had a few reports from users where they were unable to create tokens because the CVV input required more than 3 digits, despite their cards having only 3 digits CVVs.

I'm aware that with AMEX, etc. that CVVs aren't always 3 digits, however these users assured me they were using VISA. 

Normally I'd dismiss this as user error, but I got 3 reports in one evening after everything working smoothly for months. I have since disabled asking for CVV.

Stripe support has asked that I provide some info on the CC and CVV in order to debug this - but I'm having trouble extracting that info from the inputs as they are inside a secure iframe.

How can  I log the the BIN and the length the CVV input wants?

Thanks

**Comment by asolove-stripe** [comment] 2019-04-04 17:49
@scottwilson312: Yikes, that's not good! I'm trying to reproduce this and see what our logic is for CVV length and will let you know if I find anything.

Unfortunately, if you're requiring CVV and we're errorring on it being incomplete, there is no way for you to get the BIN or any other card information. I apologize that our support team asked you for this, as I don't think it's possible (without just asking your customer, which seems less-than-ideal!).

**Comment by asolove-stripe** [comment] 2019-04-04 18:15
@scottwilson312 Hmm I've tried with a variety of cards across several different places and am unable to reproduce this error. I also don't see evidence in our code that we ever require more than 3 digits in the cvc or in our logs that we are rejecting more cards than normal.

- Are you using the single Card element or the split number, expiry, cvc, elements?
- Do you know anything about the users who were having this problem? Is it possible that some other field rather than CVC was incomplete/invalid?

Thanks!

**Comment by scottwilson312** [comment] 2019-04-04 19:08
@asolove-stripe Thanks for responding. We are using  the number, expiry and cvc elements.

I don't know anything about the users other than they were located in the US. This happened a couple weeks back. We never had this issue before then it popped up a couple times in one evening, so I have a feeling it was possibly just transient.

I'll re-enable CVV and will closely monitor any tokens being denied for incomplete CVVs.

Thanks for looking into this!

**Comment by asolove-stripe** [comment] 2019-04-05 15:53
@scottwilson312: Great, please do let us know if you see any issues. I'm going to close this issue, as this wouldn't really be a bug with React Stripe Elements. But do contact support and reference this issue (and me!) if you need to escalate a problem with Stripe.js.

**Closed by asolove-stripe** 2019-04-05 15:53 UTC
