### ISSUE TITLE
Unable to call setState if token error

### ISSUE THREAD

**Issue by mintplugins** [stripe/react-stripe-elements#272] opened 2018-10-31 20:48 UTC
### Summary

This issue only seems to affect Safari OSX. In the promise function callback from the `createToken` call, if I attempt to set the state of my React component, I get this error:

`Blocked a frame with origin "https://fiddle.jshell.net" from accessing a frame with origin "https://js.stripe.com". Protocols, domains, and ports must match.`

Here's a JS Fiddle where you can see it happen (make sure you are in Safari on OSX). 
https://jsfiddle.net/wjsa45yL/1/

Steps:
1. Type an incomplete credit card number into the card form. 
2. Click "Pay"
3. See the error in the Safari console

Here is the part in the JS fiddle that matters (lines 52 to 60):
```
    const this_component = this;
    
    this.props.stripe.createToken().then(
    	function( payload ) {
        	this_component.setState({
          	      anything: 'results in safari error'
                });
         }
    );
```

### Other information

This is specific to Safari OSX for me. 
<img width="1440" alt="aqtn4d4uui" src="https://user-images.githubusercontent.com/1638128/47817685-b2087b80-dd2c-11e8-8dbe-3cafea256cff.png">

**Comment by atty-stripe** [comment] 2018-11-11 23:47
Thanks for the bug report! I'm able to reproduce in Safari on macOS as well. I'll add this to our bug tracker and keep you posted.

It looks like the setState call still succeeds though, so this isn't blocking core functionality. Does that match your experience?

**Comment by mintplugins** [comment] 2018-11-12 23:13
@atty-stripe Great thanks! Yes the state does get set, that matches my experience. The error doesn't seem to actually block any functionality as far as I can tell.

**Comment by lopezdp** [comment] 2018-12-06 17:37
I am having the same problem and receiving the same errors on my JS console.

**Comment by matt-stripe** [comment] 2018-12-19 00:36
Hello @mintplugins @lopezdp,

I'm going to close this ticket for now as my colleague @atty-stripe was unable to reproduce the behavior, if you get the chance could you re-open this with a snippet that exhibits the regressed behavior? (using JSFiddle would be great)

Thanks,
Matt

**Closed by matt-stripe** 2018-12-19 00:36 UTC

**Comment by mintplugins** [comment] 2018-12-19 16:33
@matt-stripe That's interesting. @atty-stripe Had mentioned that he did replicate, and in my screenshot above of my JSFiddle, you can see that I was getting the error on the JSFiddle I provided. 

I tested that JS Fiddle again today, and I'm not seeing it now, but it is still happening in my project. Did anything change on the Stripe end that might affect this?
