### ISSUE TITLE
This Element has already been destroyed. Please create a new one.

### ISSUE THREAD

**Issue by ijongkim** [stripe/react-stripe-elements#358] opened 2019-05-30 00:18 UTC
### Summary
Not sure if this is an issue with react-stripe-elements library but we are seeing this error in our React app using react-stripe-elements.

Upon a successful update of a user's payment token we are seeing the following error reported in Sentry:
```
IntegrationError: This Element has already been destroyed. Please create a new one.
```

It doesn't seem browser-specific as we've seen errors reported in Safari and Chrome for both desktop and mobile clients.

My best guess is that we aren't properly un-mounting the Stripe Elements and something is attempting to unmount/destroy the elements after they've already been unmounted in the React app?

Unfortunately I can't replicate it locally. Any clues you might have would be helpful, thanks!

Should we be calling `destroy()` on every element when the component unmounts?

**Comment by fred-stripe** [comment] 2019-05-30 02:49
Hi @ijongkim, very interesting issue. There's no need to explicitly `destroy()` the Stripe components as they follow the standard React lifecycle pattern. That error message is coming from Stripe.js itself rather than react-stripe-elements, and it indicates that a method was called on a `stripe.Elements`[1] instance that has already been released by Stripe.js.

In react-stripe-elements the lifecycle of the Stripe.js objects is managed by the `<Elements>` component[2] which passes this information through React's "context" mechanism[3], which we've seen cause issues at times because contexts don't seem _quite_ comfortable passing around the stateful objects that are part of the Stripe.js browser API. Unfortunately this is going to be very difficult to trace out without adding a lot of debugging calls inside the library itself.

What I can offer here is that if you are able to do an in-browser replication, you can send the relevant URL and browser info to support@stripe.com so that one of our engineers can try to reproduce on our end as well.

Now that hooks are part of React, and seeing wider usage I'm wondering if it's time to revisit #317 and see if we can eliminate some of these unusual errors.  

[1] <https://stripe.com/docs/stripe-js/reference#stripe-elements>
[2] https://github.com/stripe/react-stripe-elements/blob/6743db59fb1d9e9b11593726b0c0d56119923776/src/components/Elements.js#L67-L89
[3] https://reactjs.org/docs/context.html

**Comment by ijongkim** [comment] 2019-06-04 20:22
Hi @fred-stripe, I appreciate the quick response. Based on what you've shared with me, it doesn't sound like the problem is with our implementation. We may try to find some other clues to narrow down the situations in which this error occurs. If we are able to replicate in-browser I'll follow your suggestion and email Stripe support.

Not sure if this issue should be considered closed or not.

Thanks for your help.

**Comment by oliver-stripe** [comment] 2019-06-13 21:20
@ijongkim Thanks, I'm going to close this out for now!

**Closed by oliver-stripe** 2019-06-13 21:20 UTC

**Comment by andreyvital** [comment] 2019-10-16 12:57
Hey @ijongkim I've got a number of users surfacing this problem. Any clues?

**Comment by mdnorman** [comment] 2020-06-15 02:57
FWIW, I found that I was having this issue when the following would occur:

1. The card is rendered in a component that may end up changing based on the payment info server state
2. After awaiting the promise that changes the payment info server state, call `card.clear()` to ensure that the card info is cleared out
3. The payment info server call causes a state update that re-renders the parent component, affecting the `CardElement` in an adverse way.

**Comment by ijongkim** [comment] 2020-06-15 20:14
@andreyvital Sorry for the late response. I saw your question today. No, no clues unfortunately. I stopped investigating as I had been assigned to new tasks and projects since then.
