### ISSUE TITLE
Flow could not resolve ElementShape nor StripeShape

### ISSUE THREAD

**Issue by puradox** [stripe/react-stripe-elements#87] opened 2017-09-20 15:23 UTC
Flow is still being finicky, as usual :man_facepalming:
I believe these errors have something to do with how this library is being packaged.

I'm running the latest version of Flow, `v0.54.1`, and react-stripe-elements, `v1.0.1`.

```
Error: node_modules/react-stripe-elements/src/components/Element.js:87
 87:     _element: ElementShape;
                   ^^^^^^^^^^^^ identifier `ElementShape`. Could not resolve name

Error: node_modules/react-stripe-elements/src/components/Elements.js:11
 11:   elements: ElementsShape,
                 ^^^^^^^^^^^^^ identifier `ElementsShape`. Could not resolve name

Error: node_modules/react-stripe-elements/src/components/Elements.js:12
 12:   registerElement: (type: string, element: ElementShape) => void,
                                                ^^^^^^^^^^^^ identifier `ElementShape`. Could not resolve name

Error: node_modules/react-stripe-elements/src/components/Provider.js:11
 11:   stripe: StripeShape,
               ^^^^^^^^^^^ identifier `StripeShape`. Could not resolve name

Error: node_modules/react-stripe-elements/src/components/inject.js:73
 73:     requireElement = (specifiedType: string): ElementShape => {
                                                   ^^^^^^^^^^^^ identifier `ElementShape`. Could not resolve name

Error: node_modules/react-stripe-elements/src/components/inject.js:85
 85:     findElement = (specifiedType: string): ?ElementShape => {
                                                 ^^^^^^^^^^^^ identifier `ElementShape`. Could not resolve name


Found 6 errors
error Command failed with exit code 2.
```

**Comment by puradox** [comment] 2017-09-20 15:26
Relates with #6

**Comment by asolove-stripe** [comment] 2017-12-13 03:14
Hey @puradox, did you get a resolution to this problem? It looks like the issue is that flow is checking types on `node_modules`, which in general isn't a great idea. Recently, as of flow 0.57, it no longer checks types of files inside `node_modules` by default, so we expect this should be solved by upgrading to that or updating your config to tell flow not to run over some of your dependencies.

Because of that upstream fix with flow's config change, I think I'm going to close this issue on type failures in `node_modules/react-stipe-elements`. We'll use #6 to track questions about exporting flow types for your application to check against.

**Closed by asolove-stripe** 2017-12-13 03:14 UTC
