### ISSUE TITLE
CardElement not loading

### ISSUE THREAD

**Issue by mulholio** [stripe/react-stripe-elements#424] opened 2019-09-04 13:46 UTC
## Summary
Our card element does not load, but I can only reproduce this by refreshing and gettting the bug about 1 in 50 refreshes.

This does not appear to be a network error, as reported in https://github.com/stripe/react-stripe-elements/issues/409, and throttling does not reproduce the bug more swiftly. https://github.com/stripe/react-stripe-elements/issues/35 appears as if it might be related but I am unsure.

There are no console errors and `window.Stripe` is defined in the console.

I suspect this might have something to do with our SSR setup (with Next.js) but I am not entirely sure what. I have followed the SSR and `async` instructions in the README.

## Other information
- Occurs in both Chrome and Safari
- There appear to be differing amounts of JS loaded in the successful (first) and unsuccessful (second) cases
  - ![image](https://user-images.githubusercontent.com/20966690/64259752-93ad7680-cf21-11e9-8683-6630eb76c6ac.png)
  - ![image](https://user-images.githubusercontent.com/20966690/64259713-7bd5f280-cf21-11e9-87d0-87a4b1d70173.png)

### Correctly Loaded
![Screenshot 2019-09-04 at 14 21 21](https://user-images.githubusercontent.com/20966690/64259455-ffdbaa80-cf20-11e9-89f3-81557fdac3b3.png)

### Not Loaded
![Screenshot 2019-09-04 at 14 21 11](https://user-images.githubusercontent.com/20966690/64259458-ffdbaa80-cf20-11e9-961e-cba3c0f005d0.png)

**Comment by mbarrett-stripe** [comment] 2019-09-04 14:41
Hi @mulholio - this sounds frustrating! Maybe we can see if it's related to #35 as you said. I know you said you're not seeing console errors, but if possible, could you confirm that when this bug happens, Stripe.js is loaded and on `window` _before_ the rendering happens? Or, if you're doing the async load as you said, ensure that its either loaded _or_ the load handler fires?

Additionally, it might help to inspect the state of the element and check to see if the state provider is rigged up with a Stripe instance or not when this bug occurs, using the React dev tools to look at the state of the element.

This may be a race condition or mis-configured async load issue, but narrowing down the options can help us troubleshoot.

Thanks!

**Comment by mulholio** [comment] 2019-09-04 15:42
> could you confirm that when this bug happens, Stripe.js is loaded and on window before the rendering happens?

I'm using SSR so assume this isn't the case 

> Or, if you're doing the async load as you said, ensure that its either loaded or the load handler fires?

Dev tools info below appear to show the stripe script has loaded

Here's a screenshot of my dev tools for the `injectStripe`-wrapped component:

![image](https://user-images.githubusercontent.com/20966690/64269696-41288600-cf32-11e9-96fa-a3bd29f904dc.png)

The stripe object appears to be there

Then, the page component higher up which tracks the loading state:

![image](https://user-images.githubusercontent.com/20966690/64269637-26eea800-cf32-11e9-8179-6cb762611a60.png)

In the hooks section, `state: true` corresponds to the stripeHasLoaded variable and the object above it the Stripe object itself

**Comment by mbarrett-stripe** [comment] 2019-09-04 21:14
Hmm, and those screenshots are from an instance of the bug appearing?

Additionally, if you're able to provide an isolated reproduction case somewhere (possibly https://codesandbox.io/) that would help immensely. We will also attempt to reproduce this issue.

**Comment by mulholio** [comment] 2019-09-05 08:48
Yep, those are screenshots from the bug instance. Will have a shot on a reproduction for you

**Comment by mulholio** [comment] 2019-09-09 15:00
Haven't quite got the reproduction yet, but was getting some warnings about using `useLayoutEffect` on the server (we are currently running using a hookified version of the SSR code in the README but were getting this issue with `componentDidMount()` also) which made me wonder if this is because my code isn't running on the client at all and that's why we're not updating the stripe input element.

The code below, as well as in the README, has a `if (typeof window !== 'undefined') {` check to only run this code on the client. However, I think it might be possible that this component doesn't re-render on the client and so this code doesn't get run at all (even if it never runs on the client!)

```typescript
function useStripe() {
  const [stripe, setStripe] = useState<any>(null);
  const [stripeScriptHasLoaded, setStripeScriptHasLoaded] = useState<
    boolean
  >(false);

  useLayoutEffect(() => {
    if (typeof window !== 'undefined') {
      // The script might have already loaded by the time this effect
      // runs so set the load state here
      setStripeScriptHasLoaded(!!window.Stripe);

      if (stripeScriptHasLoaded) {
        setStripe(window.Stripe(publicRuntimeConfig.STRIPE_PUBLIC_KEY));
      } else {
        const stripeScriptTag = document.querySelector('#stripe-js');

        // This shouldn't ever run because it's static in _document.tsx:
        if (!stripeScriptTag) {
          throw new Error('could not find #stripe-js script tag');
        }

        stripeScriptTag.addEventListener('load', () => {
          setStripeScriptHasLoaded(true);
        });
      }
    }
  }, [setStripe, setStripeScriptHasLoaded, stripeScriptHasLoaded]);

  return {
    stripe,
    stripeScriptHasLoaded,
  };
}
```

This blog post seems to suggest that `componentDidMount` does not run on server either https://jaketrent.com/post/react-componentdidmount-not-called-server-render/

The use of `useLayoutEffect` here is because `useEffect` runs on server and client and this code needs to run server side. It is also meant to be closer to componentDidMount, as used in the original code example. (See Kent C Dodds' post [here](https://kentcdodds.com/blog/useeffect-vs-uselayouteffect) for more info on `useEffect` vs `useLayoutEffect`)

**Comment by tuomashatakka** [comment] 2019-10-21 14:20
I had similar problems with components not loading today. It seems like there's an issue with getting responses for the requests made to stripe's servers. 

Here's more details about my issue: https://github.com/stripe/react-stripe-elements/issues/35#issuecomment-544478819

**Comment by rishiraj824** [comment] 2019-12-02 21:12
@mulholio @mbarrett-stripe Any solutions to this? Facing the same problem.

**Comment by mattlsavage** [comment] 2019-12-04 11:49
@mulholio @mbarrett-stripe Also had reports from customers that this is happening but unable to reproduce. In this case the expiry date and cvc elements are loading but the card number field is not. No errors are being reported.

**Comment by mbarrett-stripe** [comment] 2019-12-04 15:50
Hey all, thanks for the input. Any and all info you can provide around state capture, front end error logging, etc can help us figure this issue out. As of now we have not been able to reproduce the issue, so collecting more information on setup would be helpful, and a minimum viable recreation would be excellent

**Comment by aequasi** [comment] 2020-01-06 00:11
Running into what seems to be the same, if not a very similar, issue.

The iframe loads, and I see requests to the elements endpoints. I see 2(?) inputs being created, one inside the iframe, one outside, but the cardelement has no styles, and cant be typed in. 

There are no errors on the page.

I'm also using Next.JS, but the page its on is not SSRed.

Logged out props.stripe before it renders:

![image](https://user-images.githubusercontent.com/896295/71788330-129ce380-2fd6-11ea-9d2c-0b5b108f4441.png)

**Comment by aequasi** [comment] 2020-01-06 00:37
Happening here: https://www-dgg50pjtd.now.sh/test

Theres logs available

**Comment by mbarrett-stripe** [comment] 2020-01-07 15:23
@aequasi - It appears that the page you linked is a CSS issue. If you look at the element inspector in your browser, you can see that the element is loaded, but is at 1px width. Adding a `width` style to the element makes it visible. 

I'd encourage folks to check on their problematic pages as well and see if this is in fact an issue with the element being incorrectly styled and not just that it isn't loading. You can tell for sure if you can dig down into the iframe tag inside the mounted element HTML in your inspector.

We'll continue to dig into this, and are already looking into potential ways to make it easier to avoid this styling issue and what causes it in the first place.

**Comment by karaarda** [comment] 2020-01-23 16:05
@mbarrett-stripe - We are encountering the same problem. In our case I am pretty sure the problem is not related with any CSS issue. When using client side rendering, everything works fine. However, when using SSR elements are not loaded if browser caches are enabled. Disabling the caches from network tab seems to make things work but it is not a practical solution.

I suspect it is related with some of the events being fired too early or not being fired at all when inner.html and outer.html are loaded from cache.

**Comment by orest22** [comment] 2020-01-28 17:57
@mbarrett-stripe I think we experiencing a similar issue. The page is not loading at all and the weird thing that it happens only for ios 
![Screen Shot on 2020-01-28 at 12-53-30](https://user-images.githubusercontent.com/1497502/73291147-a32da480-41cd-11ea-9e77-16aaf2015b3d.png)

**Comment by arqex** [comment] 2020-02-12 10:09
Same problem here and I could fix it.

In my case the form is rendered inside a modal that it's not visible initially, and I don't get iframe at all. The element wrapper is 0x0.

There were more than one modal trying to render the stripe form in the same page at the initialization, so it was kind of a race condition problem between those modals.

Stop loading the stripe form until the user open the modal made the trick for me. I hope this can help somebody :)

**Comment by raffjones** [comment] 2020-06-17 21:58
I'm experiencing this - no styles are loading and I get a completely non-functioning experience. I have literally copied and pasted the sample React code, but it's (a) got errors (React is not imported and it has `class=` and `for=` both of which are wrong for React. 

But what I get is this - completely default, no styling, nothing works. 

<img width="177" alt="image" src="https://user-images.githubusercontent.com/262516/84954852-15a41000-b0ee-11ea-9895-3e376b4ce830.png">

**Comment by karaarda** [comment] 2020-07-31 09:10
this problem is fixed after migrating to react-stripe-js

**Comment by sashko-stripe** [comment] 2021-03-26 18:46
Thanks for the ideas in the thread, everybody. Closing this as this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js). If you believe this is still important, please re-open it there.

**Closed by sashko-stripe** 2021-03-26 18:46 UTC
