### ISSUE TITLE
PaymentRequestButton grabbing CardElement by mistake

### ISSUE THREAD

**Issue by RobSwish** [stripe/react-stripe-elements#398] opened 2019-08-05 13:55 UTC
Hello, I hope this isn't a dumb question.

I have added a CardElement to my page that works perfectly, however, when I add a PaymentRequestButton and I try and make a payment it seems that it tries to grab the CardElement as part of `handleCardPayment`.

The card element is empty so I get an error stating that my card number is incomplete.

I'm sure I have followed the examples but I am having no luck.

I am trying to do the automatic Payment Intent flow.

Please excuse any bad code as I am new to React and Javascript 🙂 

```
stripe.confirmPaymentIntent(paymentIntentSecret, {
          payment_method: ev.paymentMethod.id,
        }).then(function(confirmResult) {
          if (confirmResult.error) {
            // Report to the browser that the payment failed, prompting it to
            // re-show the payment interface, or show an error message and close
            // the payment interface.
            console.log('Could not confirm result: ', confirmResult.error);
            return ev.complete('fail');
          } else {
            // Let Stripe.js handle the rest of the payment flow.
            stripe.handleCardPayment(paymentIntentSecret)
            .then(function(result) {
                if (result.error) {
                  console.log('Could not make Request Button payment: ', result.error);
                  return ev.complete('fail');
                }

                var invoicePaymentMade = firebase.functions().httpsCallable('invoicePaymentMade');
                var data = {
                  invoice: invoice,
                  intentID: result.paymentIntent.id
                }

                return invoicePaymentMade(data)
                .then(function(result) {
                  console.log('Request Button payment made:', result);
                  return ev.complete('success');
                }).catch(function(error) {
                  // that.setState({paying: false, failureMessage: error.message});
                  console.log('Error:', error);
                  return ev.complete('fail');
                });
              
              }).catch(function(error) {
                // that.setState({paying: false, failureMessage: error.message});
                console.log('Error:', error);
                return ev.complete('fail');
              });
            }
          }).catch(function(error) {
            var code = error.code;
            var message = error.message;
            var details = error.details;
            console.log('Error code:', code);
            console.log('Error message:', message);
            console.log('Error details:', details);
            // that.setState({paying: false, failureMessage: message});
            return ev.complete('fail');
          });
```

I can't seem to get the code to appear properly on here.

All of your examples seem to only use :

```
paymentRequest.on('token', ({complete, token, ...data}) => {
      console.log('Received Stripe token: ', token);
      console.log('Received customer information: ', data);
      complete('success');
    });
```

When using the Payment Request button, but surely this is SCA ready?

**Comment by asolove-stripe** [comment] 2019-08-09 21:10
Hi @RobSwish, thank for writing in! (And no need to excuse yourself for being new to JS/React! Our goal here is to make this library helpful enough that someone new to React can get going with Stripe, and it seems like we're not good enough at that yet.)

First off, I notice your code is first calling `confirmPaymentIntent` and then calling `handleCardPayment` if an action is required. You don't need to do that! Just calling `handleCardPayment` will do the confirmation for you, plus also handling the action if need be. So hopefully that simplifies your code a little.

Second, just like you're currently passing the payment method id in specifically to `confirmPaymentIntent`, I think you should now pass that in to `handleCardPayment` to tell us that you want to use that Payment Method rather than grab a new one from any Element. I _think_ that change would likely fix the current problem, or at least get you a different error than right now.

(BTW, you mentioned you had some trouble with code formatting, which GitHub let me fix for you. Just for future reference: if you want to do inline code snippets, you use single backticks; but for muliple line code snippets, you put three backticks on the lines before and after the code, [like this](https://help.github.com/en/articles/creating-and-highlighting-code-blocks#fenced-code-blocks).)

**Comment by ehallvard** [comment] 2019-08-27 15:51
Hi @asolove-stripe.

I got this working with only using handleCardPayment, but I find it odd since I've seen it documented several places that you should use confirmPaymentIntent as well as handleCardPayment: https://stripe.com/docs/stripe-js/elements/payment-request-button#complete-payment. 

Using both functions like the docs says seems to work, except when I try test cards that doesn't trigger 3D secure.

**Comment by ehallvard** [comment] 2019-08-28 08:17
Oh, but your advice was the only way I got it working properly :) If I do as the documentation states everything works great for 3DS cards, but using a card such as 4242 gives we the following error:

`code: "payment_intent_unexpected_state", message: "You cannot confirm this PaymentIntent because it has already succeeded after being previously confirmed."`

**Comment by AndrewOstrovsky** [comment] 2019-10-16 07:41
Hi @asolove-stripe,

I have exactly the same issue as @RobSwish, and upgrading to the latests version doesn't help.

I have both CardElement and PaymentRequestButtonElement on the same page, if i use PaymentRequestButton i'm still getting an error "Your card number is incomplete.".

I've updated `react-stripe-elements` version to 5.0.0 and i do exactly the same requests, in the same particular order as in example here -> https://stripe.com/docs/stripe-js/elements/payment-request-button#complete-payment-intents

```
await stripe.confirmPaymentIntent(clientSecret, {
    payment_method: ev.paymentMethod.id
})

await stripe.handleCardPayment(clientSecret)
```

I have a feeling it's actually related to https://github.com/stripe/react-stripe-elements/issues/442 and https://github.com/stripe/react-stripe-elements/issues/365, rather than only using handleCardPayment without confirmPaymentIntent.

On the side note, why would i need to use  confirmPaymentIntent if docs clearly says it's optional, and not needed for automatic payment flow, which @RobSwish mentioned initially?

> Only use this method if you want to handle next actions yourself. Otherwise, use stripe.handleCardPayment.

https://stripe.com/docs/stripe-js/reference#stripe-confirm-payment-intent-no-element

Thanks in advance!

**Comment by sashko-stripe** [comment] 2021-03-26 18:39
Closing this as this project has migrated to [React Stripe.js](https://github.com/stripe/react-stripe-js) as of early 2020, which also has a somewhat different API. If you believe this is still important, please re-open it there.

**Closed by sashko-stripe** 2021-03-26 18:39 UTC
