### ISSUE TITLE
TypeError: Cannot read property 'paymentRequest' of undefined

### ISSUE THREAD

**Issue by Emixam23** [stripe/react-stripe-elements#173] opened 2018-02-18 18:16 UTC
Hey,

I am currently trying to integrate stripe (an alpha) with React.JS. I already made it works with Xamarin (.NET), however, with ReactJS, it seems quite different. I so followed your tutorial react-stripe-elements, however, I am facing this and I don't get why.

[![enter image description here][1]][1]

There is my `index.js`

    import React from 'react'
    import { render } from 'react-dom'

    import { Provider } from 'react-redux'
    import { createStore, applyMiddleware, compose } from 'redux'
    import ReduxPromise from 'redux-promise'
    import thunk from 'redux-thunk'

    import { BrowserRouter as Router, Route, Switch } from 'react-router-dom'

    import App from './app'

    import Home from './pages/home/home'
    import Collections from './pages/articles/collections/collections'
    import Glasses from './pages/articles/glasses/glasses'
    import Watches from './pages/articles/watches/watches'
    import Bracelets from './pages/articles/bracelets/bracelets';

    import Login from './pages/auth/login/login';
    import Register from './pages/auth/register/register';

    import ShoppingBag from './pages/shopping/shopping-bag/shopping-bag';
    import Order from './pages/shopping/order/order';

    import ArticleDetails from './pages/articles/article-details/article-details';

    import root_reducer from './shop/root_reducer';
    import Support from './pages/support/conversations/support';
    import NewConversation from './pages/support/new-conversation/new-conversation';

    import { StripeProvider } from 'react-stripe-elements';

    let store = createStore(root_reducer, compose(
        applyMiddleware(ReduxPromise, thunk),
        window.devToolsExtension ? window.devToolsExtension() : f => f))

    render(
        <Provider store={store}>
            <StripeProvider apiKey="xx_xxxxx_xxxxxxxxxxxxx">
                <Router>
                    <App>
                        <Switch>
                            <Route exact path="/" component={Home}/>
                            <Route path="/home" component={Home}/>

                            <Route path="/collections" component={Collections}/>
                            <Route path="/bracelets" component={Bracelets}/>
                            <Route path="/glasses" component={Glasses}/>
                            <Route path="/watches" component={Watches}/>

                            <Route path="/shopping_bag" component={ShoppingBag}/>
                            <Route path="/order" component={Order}/>

                            <Route path="/login" component={Login}/>
                            <Route path="/register" component={Register}/>

                            <Route path="/article/:id" component={ArticleDetails}/>

                            <Route path="/support" component={Support}/>
                            <Route path="/new_message" component={NewConversation}/>
                        </Switch>
                    </App>
                </Router>
            </StripeProvider>
        </Provider>,
        document.getElementById('root')
    )

As you can see, the stripe provider is defined higher than my `Order` component, so where am I wrong?

Thanks for any help

  [1]: https://i.stack.imgur.com/QPTbL.png

**Comment by cweiss-stripe** [comment] 2018-02-19 14:15
Hi @Emixam23 
Thanks for reporting your issue.
Seeing that you are using redux and react-stripe-elements, my first guess is that the issue is due to the interaction of `injectStripe` and `connect`.
We have a short troubleshooting guide about those here: https://github.com/stripe/react-stripe-elements#troubleshooting
Could you check if your error can be resolved that way?

**Comment by asolove-stripe** [comment] 2018-09-10 16:42
Hey @Emixam23, did you ever figure this out? From your example code, it looks like you were referencing `prop.stripe` before it would have been injected. So I hope the solution was as simple as waiting for it to be there. 

I'm going to close this, as it's been a while without an update and it seems like not an issue with react-stripe-elements itself. That said, if the suggestion above didn't work for you, I'm very happy to reopen and discuss further.

**Closed by asolove-stripe** 2018-09-10 16:42 UTC

**Comment by Emixam23** [comment] 2018-09-11 22:27
Hey !

Sorry if I never replied :/ I think I found a workaround when I was working on this, there is the code:

    import React from 'react'
    import { render } from 'react-dom'

    import { Provider } from 'react-redux'
    import { createStore, applyMiddleware, compose } from 'redux'
    import ReduxPromise from 'redux-promise'
    import thunk from 'redux-thunk'

    import { BrowserRouter as Router, Route, Switch } from 'react-router-dom'

    import App from './app'

    import Home from './pages/home/home'
    import Collections from './pages/articles/collections/collections'
    import Glasses from './pages/articles/glasses/glasses'
    import Watches from './pages/articles/watches/watches'
    import Bracelets from './pages/articles/bracelets/bracelets';

    import Login from './pages/auth/login/login';
    import Register from './pages/auth/register/register';

    import ShoppingBag from './pages/shopping/shopping-bag/shopping-bag';
    import Order from './pages/shopping/order/order';

    import ArticleDetails from './pages/articles/article-details/article-details';

    import root_reducer from './shop/root_reducer';
    import Support from './pages/support/conversations/support';
    import NewConversation from './pages/support/new-conversation/new-conversation';

    import { StripeProvider, Elements } from 'react-stripe-elements';

    let store = createStore(root_reducer, compose(
        applyMiddleware(ReduxPromise, thunk),
        window.devToolsExtension ? window.devToolsExtension() : f => f))

    render(
        <Provider store={store}>
            <StripeProvider apiKey="xx_xxxxx_xxxxxxxxxxxxx">
                <Router>
                    <App>
                        <Switch>
                            <Route exact path="/" component={Home}/>
                            <Route path="/home" component={Home}/>

                            <Route path="/collections" component={Collections}/>
                            <Route path="/bracelets" component={Bracelets}/>
                            <Route path="/glasses" component={Glasses}/>
                            <Route path="/watches" component={Watches}/>

                            <Route path="/shopping_bag" component={ShoppingBag}/>

                            <Route path="/login" component={Login}/>
                            <Route path="/register" component={Register}/>

                            <Route path="/article/:id" component={ArticleDetails}/>

                            <Route path="/support" component={Support}/>
                            <Route path="/new_message" component={NewConversation}/>
                            
                            <Elements>
                                <Route path="/order" component={Order}/>
                            </Elements>
                        </Switch>
                    </App>
                </Router>
            </StripeProvider>
        </Provider>,
        document.getElementById('root')
    )

**Comment by asolove-stripe** [comment] 2018-09-12 01:04
Sounds good, glad you found a solution!
