### ISSUE TITLE
Using tab index with multiple CardXxxElements

### ISSUE THREAD

**Issue by talkingtab** [stripe/react-stripe-elements#281] opened 2018-11-28 19:49 UTC
I'm using material-ui with react-stripe-elments and have code like this
```
<CardContent style={{ paddingTop: "5px", paddingBottom: "5px" }}>
    <Typography variant="subtitle1">Card Number</Typography>
    <CardNumberElement/>
</CardContent>
<CardContent style={{ paddingTop: "5px", paddingBottom: "5px" }}>
    <Typography variant="subtitle1">Card Expiration</Typography>
    <CardExpiryElement />
</CardContent>
```
I would like to allow the user to tab between fields. Is that possible? If not is there a way to style the <CardElement/> so that each field is on a separate line? 
thanks!

**Comment by fred-stripe** [comment] 2018-11-29 18:46
@talkingtab Elements should respect the page's tab order. What elements does material-ui render here in the DOM, and what behavior are you seeing? Would you be able to share URL with a full reproduction so we could take a closer look?

**Comment by talkingtab** [comment] 2018-11-30 03:15
@fred-stripe Thanks. Looking at this, I'm wondering if it has to do with possibly being in a React Portal component. I'm still wandering in the dark on this. I go the demo to work just fine, then put the component into a material-ui  Dialog and it fails.  The react portal doc points to this issue: `https://reactjs.org/docs/accessibility.html#programmatically-managing-focus` I want the payment window to be in some sort of pop up or overlay or something like that.

**Comment by matt-stripe** [comment] 2018-12-19 00:35
Hello @talkingtab,

Please reach out again if you happen to find a bug (reproducible code snippets as @fred-stripe says would be the best here). I'm going to close this for now since I'm not able to reproduce the behavior locally with no frameworks (i.e. not using `material-ui`).

Thanks,
Matt

**Closed by matt-stripe** 2018-12-19 00:35 UTC
